/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.historia.menuHistoria;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class menu extends javax.swing.JFrame {

    ImageIcon hoverBtnIcon, defaultBtnIcon;
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        hoverBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn-active.png"));
        defaultBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        btn_versus = new javax.swing.JButton();
        lbl_btn_versus = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        lbl_btn_salir = new javax.swing.JLabel();
        btn_jugador1 = new javax.swing.JButton();
        lbl_btn_jugador1 = new javax.swing.JLabel();
        btn_historia = new javax.swing.JButton();
        lbl_btn_historia = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Challenge04 - Menú Principal");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btn_versus.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        btn_versus.setForeground(new java.awt.Color(255, 255, 255));
        btn_versus.setText("Versus");
        btn_versus.setBorder(null);
        btn_versus.setBorderPainted(false);
        btn_versus.setContentAreaFilled(false);
        btn_versus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_versus.setFocusPainted(false);
        btn_versus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_versusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_versusMouseExited(evt);
            }
        });
        btn_versus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_versusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_versus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 180, 40));

        lbl_btn_versus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_versus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 70));

        btn_salir.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.setFocusPainted(false);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        btn_salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_salirKeyPressed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 180, 40));

        lbl_btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 200, 70));

        btn_jugador1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        btn_jugador1.setForeground(new java.awt.Color(255, 255, 255));
        btn_jugador1.setText("Jugador 1");
        btn_jugador1.setBorder(null);
        btn_jugador1.setBorderPainted(false);
        btn_jugador1.setContentAreaFilled(false);
        btn_jugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_jugador1.setFocusPainted(false);
        btn_jugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jugador1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jugador1MouseExited(evt);
            }
        });
        btn_jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jugador1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, 40));

        lbl_btn_jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 70));

        btn_historia.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        btn_historia.setForeground(new java.awt.Color(255, 255, 255));
        btn_historia.setText("Modo Historia");
        btn_historia.setBorder(null);
        btn_historia.setBorderPainted(false);
        btn_historia.setContentAreaFilled(false);
        btn_historia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_historia.setFocusPainted(false);
        btn_historia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_historiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_historiaMouseExited(evt);
            }
        });
        btn_historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 40));

        lbl_btn_historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 70));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salirKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_salirKeyPressed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jugador1ActionPerformed
        // TODO add your handling code here:
        dispose();
        modojugador modoJugador = new modojugador(false);
        modoJugador.setVisible(true);
    }//GEN-LAST:event_btn_jugador1ActionPerformed

    private void btn_versusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_versusActionPerformed
        // TODO add your handling code here:
        dispose();
        modojugador modoJugador = new modojugador(true);
        modoJugador.setVisible(true);
    }//GEN-LAST:event_btn_versusActionPerformed

    private void btn_historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historiaActionPerformed
        menuHistoria menuH = new menuHistoria();
        menuH.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_historiaActionPerformed

    private void btn_historiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historiaMouseEntered
        // TODO add your handling code here:
        lbl_btn_historia.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_historiaMouseEntered

    private void btn_historiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historiaMouseExited
        // TODO add your handling code here:
        lbl_btn_historia.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_historiaMouseExited

    private void btn_jugador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jugador1MouseEntered
        // TODO add your handling code here:
        lbl_btn_jugador1.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_jugador1MouseEntered

    private void btn_jugador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jugador1MouseExited
        // TODO add your handling code here:
        lbl_btn_jugador1.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_jugador1MouseExited

    private void btn_versusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_versusMouseEntered
        // TODO add your handling code here:
        lbl_btn_versus.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_versusMouseEntered

    private void btn_versusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_versusMouseExited
        // TODO add your handling code here:
        lbl_btn_versus.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_versusMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        // TODO add your handling code here:
        lbl_btn_salir.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        // TODO add your handling code here:
        lbl_btn_salir.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_historia;
    private javax.swing.JButton btn_jugador1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_versus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lbl_btn_historia;
    private javax.swing.JLabel lbl_btn_jugador1;
    private javax.swing.JLabel lbl_btn_salir;
    private javax.swing.JLabel lbl_btn_versus;
    private javax.swing.JLabel lbl_icon;
    // End of variables declaration//GEN-END:variables
}
