/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.message;

import challenge04.sound;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class customMessage extends javax.swing.JDialog {

    ImageIcon hoverBtnCloseIcon, defaultBtnCloseIcon, hoverBtnOkIcon, defaultBtnOKIcon;
    sound Sound = new sound();
    /**
     * Creates new form customMessage
     * @param parent
     * @param modal
     */
    public customMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setUndecorated(true);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        
        initComponents();
        
        pnl_principal.setBackground(new Color(0, 0, 0, 0));
    }
    
    /**
     * Creates new form customMessage
     * @param parent
     * @param modal
     * @param message
     */
    public customMessage(java.awt.Frame parent, boolean modal, String message) {
        super(parent, modal);
        
        setUndecorated(true);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        
        initComponents();
        
        pnl_principal.setBackground(new Color(0, 0, 0, 0));
        txt_message.setText(message);
        
        hoverBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close-active.png"));
        defaultBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close.png"));
        
        hoverBtnOkIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-ok-active.png"));
        defaultBtnOKIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-ok.png"));
        
        lbl_cerrar.setIcon(defaultBtnCloseIcon);
        lbl_btn_ok.setIcon(defaultBtnOKIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        btn_ok = new javax.swing.JButton();
        lbl_btn_ok = new javax.swing.JLabel();
        lbl_cerrar = new javax.swing.JLabel();
        txt_message = new javax.swing.JTextPane();
        lbl_content = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        pnl_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ok.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("Aceptar");
        btn_ok.setBorder(null);
        btn_ok.setBorderPainted(false);
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.setFocusPainted(false);
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_okMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_okMouseExited(evt);
            }
        });
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        pnl_principal.add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 127, 220, 60));
        pnl_principal.add(lbl_btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 80));

        lbl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseExited(evt);
            }
        });
        pnl_principal.add(lbl_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 50));

        txt_message.setEditable(false);
        txt_message.setBorder(null);
        txt_message.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_message.setFocusable(false);
        txt_message.setOpaque(false);
        pnl_principal.add(txt_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 70));

        lbl_content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/message/content-message.png"))); // NOI18N
        pnl_principal.add(lbl_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 450, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void lbl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseExited
        // TODO add your handling code here:
        lbl_cerrar.setIcon(defaultBtnCloseIcon);
    }//GEN-LAST:event_lbl_cerrarMouseExited

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        Sound.reproducirSonido(this, 0);
        dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseEntered
        // TODO add your handling code here:
        lbl_btn_ok.setIcon(hoverBtnOkIcon);
    }//GEN-LAST:event_btn_okMouseEntered

    private void btn_okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseExited
        // TODO add your handling code here:
        lbl_btn_ok.setIcon(defaultBtnOKIcon);
    }//GEN-LAST:event_btn_okMouseExited

    private void lbl_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseEntered
        // TODO add your handling code here:
        lbl_cerrar.setIcon(hoverBtnCloseIcon);
    }//GEN-LAST:event_lbl_cerrarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                customMessage dialog = new customMessage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_btn_ok;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_content;
    private javax.swing.JPanel pnl_principal;
    private javax.swing.JTextPane txt_message;
    // End of variables declaration//GEN-END:variables
}
