/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import static challenge04.main.vidas_historia;
import static challenge04.main.alma_etapa;
import challenge04.sound;
import java.awt.*;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class alma extends javax.swing.JFrame {

    String[] titulos = {
        "ALMA",
        "Importancia del café",
        "Expedición de Alma",
        "Alma en Riohacha",
        "Alma en Cartagena",
        "Pasantía en Quibdó"
    };
    String[] contextos = {
        "Alma nace del sentimiento y necesidad de muchos de los niños de Uribia que pasan hambre diariamente, por eso Alma nace con el fin de combatir las necesidades básicas insatisfechas. La inseguridad alimentaria y desnutrición, mediante acciones y compartiendo conocimiento que desarrollará en su aventura. Alma debe adquirir conocimiento, ayúdala a pasar su educación en la escuela Alfonso López Pumarejo, pero debe conocer sobre sus tierras de origen. Alma requiere aprender primero bases e información importante para combatir el hambre, pero como todo niño debe empezar por la escuela.",
        "La producción de café en Urumita es fundamental para la economía local, ya que más del 2.83% de la producción nacional proviene de esta región. Urumita, conocida como 'El Jardín del Sur de La Guajira'.",
        "Alma, en una de las expediciones de la escuela, viaja al municipio vecino de Distracción y ve cultivos de fríjol guajiro secos por el clima.",
        "Alma ha crecido en su manera de pensar y visualizar su entorno, por lo cual sigue su educación en Riohacha.",
        "En esta etapa llega a Cartagena y ve que, en barrios pobres como Olaya Herrera, el 50% de los niños tienen anemia. Una nutricionista le explica: 'En esta etapa llega a Cartagena y ve que, en barrios pobres como Olaya Herrera, el 50% de los niños tienen anemia.'",
        "Alma aprendió mucho. Finalmente, deciden hacer una pasantía en Quibdó, en el barrio El Reposo."
    };
    
    private Point mouseClickPoint;
    ImageIcon hoverBtnIcon, defaultBtnIcon, hoverBtnCloseIcon, defaultBtnCloseIcon, hoverBtnMiniIcon, defaultBtnMiniIcon;

    public alma() {
        initComponents();
        
        hoverBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn-active.png"));
        defaultBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn.png"));

        hoverBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close-active.png"));
        defaultBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close.png"));
        
        hoverBtnMiniIcon = new ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini-active.png"));
        defaultBtnMiniIcon = new ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini.png"));

        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        lbl_btn_responder.setVisible(false);

        LbTitulo.setText(titulos[alma_etapa]);
        TAparrafo.setText(contextos[alma_etapa]);
        switch (vidas_historia) {
            case 1 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
            }
            case 2 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(false);
            }
            case 3 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(true);
            }
            default -> {
                lbvida1.setVisible(false);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStart = new javax.swing.JPanel();
        pnl_bar = new javax.swing.JPanel();
        lbl_close_window = new javax.swing.JLabel();
        lbl_mini_window = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        TAparrafo = new javax.swing.JTextArea();
        LbContinuar = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        BtnResponder = new javax.swing.JButton();
        lbl_btn_responder = new javax.swing.JLabel();
        lbvida1 = new javax.swing.JLabel();
        lbvida2 = new javax.swing.JLabel();
        lbvida3 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Challenge04");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlStart.setBackground(new java.awt.Color(255, 255, 255));
        pnlStart.setMinimumSize(new java.awt.Dimension(480, 480));
        pnlStart.setPreferredSize(new java.awt.Dimension(480, 488));
        pnlStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bar.setOpaque(false);
        pnl_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barMouseDragged(evt);
            }
        });
        pnl_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barMousePressed(evt);
            }
        });
        pnl_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/message/btn-message-close.png"))); // NOI18N
        lbl_close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseExited(evt);
            }
        });
        pnl_bar.add(lbl_close_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 50));

        lbl_mini_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini.png"))); // NOI18N
        lbl_mini_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseExited(evt);
            }
        });
        pnl_bar.add(lbl_mini_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, 50));

        pnlStart.add(pnl_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        pnlStart.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        TAparrafo.setEditable(false);
        TAparrafo.setBackground(new java.awt.Color(255, 255, 255));
        TAparrafo.setColumns(20);
        TAparrafo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TAparrafo.setForeground(new java.awt.Color(255, 255, 255));
        TAparrafo.setLineWrap(true);
        TAparrafo.setRows(5);
        TAparrafo.setWrapStyleWord(true);
        TAparrafo.setAutoscrolls(false);
        TAparrafo.setBorder(null);
        TAparrafo.setFocusable(false);
        TAparrafo.setOpaque(false);
        TAparrafo.setPreferredSize(new java.awt.Dimension(380, 110));
        TAparrafo.setVerifyInputWhenFocusTarget(false);
        pnlStart.add(TAparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 660, 220));

        LbContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbContinuar.setForeground(new java.awt.Color(255, 153, 0));
        LbContinuar.setText("Presione cualquier tecla para continuar...");
        pnlStart.add(LbContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 290, -1));

        LbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(255, 153, 0));
        LbTitulo.setText("\"\"");
        pnlStart.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        BtnResponder.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        BtnResponder.setForeground(new java.awt.Color(255, 255, 255));
        BtnResponder.setText("Ir a la pregunta");
        BtnResponder.setBorder(null);
        BtnResponder.setBorderPainted(false);
        BtnResponder.setContentAreaFilled(false);
        BtnResponder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnResponder.setFocusPainted(false);
        BtnResponder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResponderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnResponderMouseExited(evt);
            }
        });
        BtnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResponderActionPerformed(evt);
            }
        });
        pnlStart.add(BtnResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 433, 170, 50));

        lbl_btn_responder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        pnlStart.add(lbl_btn_responder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 200, 60));

        lbvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        lbvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        lbvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background_general.png"))); // NOI18N
        pnlStart.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStart, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStart, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarBoton() {
        BtnResponder.setVisible(true);
        BtnResponder.setEnabled(true);
        lbl_btn_responder.setVisible(true);
        LbContinuar.setVisible(false);
    }
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.print(alma_etapa);
        if (alma_etapa == 0) {
            mostrarBoton();
            LbTitulo.setText("ALMA EN LA ESCUELA");
            TAparrafo.setText("""
                              La guajira en materia agrícola produce diferentes productos como lo son: maíz en los municipios de Hatonuevo, Albania, el Molino, San Juan del Cesar y Barrancas, el plátano en los municipios de Dibulla, el arroz en el municipio de Distracción y Fonseca, el café en La Jagua del Pilar, Villanueva y Urumita, el frijol en Maicao y la yuca en Riohacha, según el EVA 2021.
                              Alma debe identificar sus raíces y los productos autóctonas de la zona geográfica.
                              															
                              """);

        }

        if (alma_etapa == 1) {
            mostrarBoton();
            LbTitulo.setText("URUMITA");
            TAparrafo.setText("""
                              Urumita es hogar de por lo menos 500 familias que dependen del café para su sustento. Urumita produce café arábigo de altura, pero no tienen maquinaria para procesarlo. Los intermediarios les pagan 2,000 por kilo y lo venden en 20,000.""");
        }
        if (alma_etapa == 2) {
            mostrarBoton();
            LbTitulo.setText("MUNICIPIO DE DISTRACOM");
            TAparrafo.setText("""
                              Un nativo agrónomo le dice: Que esta semilla ancestral resiste sequías, pero casi no se usa, que la mayoría  de los jóvenes se van a Venezuela por falta de oportunidades. """);
        }
        if (alma_etapa == 3) {
            mostrarBoton();
            LbTitulo.setText("RIOHACHA");
            TAparrafo.setText("""
                              Una de las primeras cosas que observa es como niños muy pequeños y parecidos a los de su natal municipio de igual manera flacos buscan comida hasta en cestas de basura. Lleva su inquietud a su maestra le dice que
                              El pescado es el principal alimento, pero la contaminación por plásticos redujo la pesca en 40% (INVEMAR, 2023) y Los comedores comunitarios solo dan alimento 3 días a la semana.""");
        }
        if (alma_etapa == 4) {
            mostrarBoton();
            LbTitulo.setText("CARTAGENA");
            TAparrafo.setText("""
                              En categena de Indias, Hay huertos urbanos, pero las personas no saben cocinar lo que cosechan. """);
        }
        if (alma_etapa == 5) {
            mostrarBoton();
            LbTitulo.setText("EMPODERAMIENTO");
            TAparrafo.setText("""
                              Alma conoce a mujeres afro que cultivan chontaduro, pero no pueden venderlo. Una líder le cuenta:
                              Los mercados están lejos y el transporte es caro y los hombres controlan los ingresos familiares.""");
        }


        /*
         */

    }//GEN-LAST:event_formKeyPressed

    private void BtnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResponderActionPerformed
        sound.getInstance().reproducirSonido(this, 0);
        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        lbl_btn_responder.setVisible(false);
        LbContinuar.setVisible(true);
        almaPreguntas Alma = new almaPreguntas();
        dispose();
        Alma.setVisible(true);
    }//GEN-LAST:event_BtnResponderActionPerformed

    private void lbl_close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_close_windowMouseClicked

    private void lbl_close_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseEntered
        // TODO add your handling code here:
        lbl_close_window.setIcon(hoverBtnCloseIcon);
    }//GEN-LAST:event_lbl_close_windowMouseEntered

    private void lbl_close_windowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseExited
        // TODO add your handling code here:
        lbl_close_window.setIcon(defaultBtnCloseIcon);
    }//GEN-LAST:event_lbl_close_windowMouseExited

    private void lbl_mini_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseClicked
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbl_mini_windowMouseClicked

    private void lbl_mini_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseEntered
        // TODO add your handling code here:
        lbl_mini_window.setIcon(hoverBtnMiniIcon);
    }//GEN-LAST:event_lbl_mini_windowMouseEntered

    private void lbl_mini_windowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseExited
        // TODO add your handling code here:
        lbl_mini_window.setIcon(defaultBtnMiniIcon);
    }//GEN-LAST:event_lbl_mini_windowMouseExited

    private void pnl_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barMouseDragged
        // TODO add your handling code here:
        Point frameLocation = getLocation();
        int x = frameLocation.x + evt.getX() - mouseClickPoint.x;
        int y = frameLocation.y + evt.getY() - mouseClickPoint.y;
        setLocation(x, y);
    }//GEN-LAST:event_pnl_barMouseDragged

    private void pnl_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barMousePressed
        // TODO add your handling code here:
        mouseClickPoint = evt.getPoint();
    }//GEN-LAST:event_pnl_barMousePressed

    private void BtnResponderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResponderMouseEntered
        // TODO add your handling code here:
        lbl_btn_responder.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnResponderMouseEntered

    private void BtnResponderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResponderMouseExited
        // TODO add your handling code here:
        lbl_btn_responder.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnResponderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnResponder;
    private javax.swing.JLabel LbContinuar;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextArea TAparrafo;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_btn_responder;
    private javax.swing.JLabel lbl_close_window;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_mini_window;
    private javax.swing.JLabel lbvida1;
    private javax.swing.JLabel lbvida2;
    private javax.swing.JLabel lbvida3;
    private javax.swing.JPanel pnlStart;
    private javax.swing.JPanel pnl_bar;
    // End of variables declaration//GEN-END:variables
}
