/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import GUI.message.customMessage;
import static challenge04.main.*;

/**
 *
 * @author Jimmi
 */
public class almaPreguntas extends javax.swing.JFrame {

    String[] preguntas = {
        "¿Qué producto se da en su natal Urumita?",
        "El pensamiento que tiene a Alma respecto a esto sería, Que en futuro se podría:",
        "El nativo le pregunta a Alma ¿Qué acción revitalizaría la economía local? ",
        "La maestra le pregunta a Alma: ¿Qué solución combate el hambre y protege el mar simultáneamente?",
        "¿Qué proyecto integrado combate el hambre aquí?",
        "¿Cómo empoderar a estas mujeres y combatir el hambre? "
    };

    String[][] opciones = {
        {"Maíz", "Arroz", "Café", "Frijol"},
        {"Pedir subsidios al gobierno", "Montar un taller local para tostar y empacar el café", "Vender el café a multinacionales", "Cambiar a cultivos de coca"},
        {"Usar transgénicos para aumentar producción", "Crear un banco de semillas de frijol guajiro y venderlo como producto gourmet", "Convertir la tierra en pastizales para ganado", "Esperar lluvias"},
        {"Repartir más comida procesada ", "Crear una red de pesca sostenible y limpieza de manglares", "Importar carne de res", "Construir un puerto pesquero industrial"},
        {"Dar bonos para comprar en supermercados", "Talleres de cocina con productos de huertos + venta de excedentes", "Repartir suplementos de hierro ", "Construir un McDonald`s comunitario"},
        {"Pedir ayuda a ONGs internacionales", "Crear una cooperativa de mujeres para hacer harina de chontaduro ", "Esperar a que el gobierno construya carreteras", "Vender las tierras a empresas"}
    };

    public almaPreguntas() {
        initComponents();
        //reproducirSonido();
        int i = alma_etapa;
        switch (vidas_historia) {
            case 1:
                lbvida1.setVisible(true);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
                break;
            case 2:
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(false);
                break;
            case 3:
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(true);
                break;
            default:
                lbvida1.setVisible(false);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
        }
        LbPregunta.setText(preguntas[i]);
        RB1.setText(opciones[i][0]);
        RB2.setText(opciones[i][1]);
        RB3.setText(opciones[i][2]);
        RB4.setText(opciones[i][3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbPregunta = new javax.swing.JTextArea();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        BtnRespuesta = new javax.swing.JButton();
        lbl_btn_respuesta = new javax.swing.JLabel();
        lbvida1 = new javax.swing.JLabel();
        lbvida2 = new javax.swing.JLabel();
        lbvida3 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alma_Niña .png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHALLENGE 04");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alma_Niña .png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 110, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 6, -1, -1));

        LbPregunta.setEditable(false);
        LbPregunta.setColumns(20);
        LbPregunta.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LbPregunta.setForeground(new java.awt.Color(255, 153, 0));
        LbPregunta.setLineWrap(true);
        LbPregunta.setRows(5);
        LbPregunta.setWrapStyleWord(true);
        LbPregunta.setBorder(null);
        LbPregunta.setFocusable(false);
        LbPregunta.setOpaque(false);
        jPanel1.add(LbPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 630, 70));

        buttonGroup1.add(RB1);
        RB1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RB1.setForeground(new java.awt.Color(255, 255, 255));
        RB1.setContentAreaFilled(false);
        jPanel1.add(RB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        buttonGroup1.add(RB2);
        RB2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RB2.setForeground(new java.awt.Color(255, 255, 255));
        RB2.setContentAreaFilled(false);
        jPanel1.add(RB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        buttonGroup1.add(RB3);
        RB3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RB3.setForeground(new java.awt.Color(255, 255, 255));
        RB3.setContentAreaFilled(false);
        jPanel1.add(RB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        buttonGroup1.add(RB4);
        RB4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RB4.setForeground(new java.awt.Color(255, 255, 255));
        RB4.setContentAreaFilled(false);
        jPanel1.add(RB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        BtnRespuesta.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        BtnRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        BtnRespuesta.setText("Enviar  Respuesta");
        BtnRespuesta.setBorder(null);
        BtnRespuesta.setBorderPainted(false);
        BtnRespuesta.setContentAreaFilled(false);
        BtnRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRespuesta.setFocusPainted(false);
        BtnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 50));

        lbl_btn_respuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, 60));

        lbvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        jPanel1.add(lbvida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        lbvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        jPanel1.add(lbvida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        lbvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        jPanel1.add(lbvida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background_general.png"))); // NOI18N
        jPanel1.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRespuestaActionPerformed
        int alma_respuesta = 0;
        if (buttonGroup1.getSelection() != null) {

            if (RB1.isSelected()) {
                alma_respuesta = 1;
            } else if (RB2.isSelected()) {
                alma_respuesta = 2;
            } else if (RB3.isSelected()) {
                alma_respuesta = 3;
            } else if (RB4.isSelected()) {
                alma_respuesta = 4;
            }

            if (alma_correcta[alma_etapa] == alma_respuesta) {
                alma_etapa++;
                LbPregunta.setText("");
                dispose();
                if (alma_etapa < 6 && vidas_historia > 0) {
                    alma Alma = new alma();
                    Alma.setVisible(true);
                } else {
                    edu_etapa_bloqueada = false;
                    menuHistoria menuH = new menuHistoria();
                    dispose();

                    menuH.setVisible(true);
                }
                
            } else {
                //JOptionPane.showMessageDialog(this, "Error, intente nuevamente");
                customMessage dialog = new customMessage(this, true, "Incorrecto, vamos de nuevo");
                dialog.setVisible(true);
                vidas_historia--;
                dispose();
                if (alma_etapa < 6 && vidas_historia > 0) {
                    alma Alma = new alma();
                    Alma.setVisible(true);
                } else {
                    menuHistoria menuH = new menuHistoria();
                    dispose();
                    vidas_historia = 3;
                    alma_etapa = 0;
                    menuH.setVisible(true);
                }
            }

        } else {
            //JOptionPane.showMessageDialog(null, "Ninguna opción seleccionada");
            customMessage dialog = new customMessage(this, true, "Ninguna opción seleccionada");
            dialog.setVisible(true);
        }


    }//GEN-LAST:event_BtnRespuestaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new almaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRespuesta;
    private javax.swing.JTextArea LbPregunta;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_btn_respuesta;
    private javax.swing.JLabel lbvida1;
    private javax.swing.JLabel lbvida2;
    private javax.swing.JLabel lbvida3;
    // End of variables declaration//GEN-END:variables
}
