/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import static challenge04.main.alma_etapa;

/**
 *
 * @author david
 */
public class alma extends javax.swing.JFrame {
    String[] titulos = {
    "ALMA",
    "Importancia del cafe",
    "Expedicion de alma",
    "Alma en Riohacha",
    "Alma en Cartagena",
    "Pasantia en Quibdo"
};    
    String[] contextos = {
    "Alma nace del sentimiento y necesidad de muchos de los niños de Uribia que pasan hambre diariamente, por eso Alma nace con el fin de combatir las necesidades básicas insatisfechas. La inseguridad alimentaria y desnutrición mediante acciones y compartiendo conocimiento que desarrollara en su aventura, Alma debe adquirir conocimiento, ayúdala a pasar su educación en la escuela Alfonso López Pumarejoro pero debe conocer sobre sus tierras de origen. Alma requiere aprender primero bases e información importante para combatir el hambre, pero como todo niño debe empezar por la calle.",
    "La producción de café en Urumita es fundamental para la economía local, ya que más del 2.83% de la producción nacional proviene de esta región. Urumita, conocida como El Jardín del Sur de La Guajira",
    "Alma en una de las expediciones de la escuela viaja al municipio vecino de Distracción ve cultivos de frijol guajiro secos por el clima.",
    "Alma ha crecido en su manera de pensar y visualizar su entorno por lo cual sigue su educación en Riohacha.",
    "En esta etapa llega a Cartagena y ve que, en barrios pobres como Olaya Herrera, el 50% de los niños tienen anemia. Una nutricionista le explica: En esta etapa llega a Cartagena y ve que, en barrios pobres como Olaya Herrera, el 50% de los niños tienen anemia. Una nutricionista le explica:",
    "Alma aprendió mucho. Finalmente deciden hacer una pasantía en el Quibdo en el Barrio el reposo"
};
    public alma() {
        initComponents();
        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        int p = alma_etapa;
        LbTitulo.setText(titulos[p]);
        TAparrafo.setText(contextos[p]);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TAparrafo = new javax.swing.JTextArea();
        LbContinuar = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        BtnResponder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Challenge04");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlStart.setBackground(new java.awt.Color(255, 255, 255));
        pnlStart.setMinimumSize(new java.awt.Dimension(480, 480));
        pnlStart.setPreferredSize(new java.awt.Dimension(480, 488));
        pnlStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        pnlStart.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        TAparrafo.setEditable(false);
        TAparrafo.setBackground(new java.awt.Color(255, 255, 255));
        TAparrafo.setColumns(20);
        TAparrafo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TAparrafo.setForeground(new java.awt.Color(0, 102, 102));
        TAparrafo.setLineWrap(true);
        TAparrafo.setRows(5);
        TAparrafo.setWrapStyleWord(true);
        TAparrafo.setAutoscrolls(false);
        TAparrafo.setBorder(null);
        TAparrafo.setFocusable(false);
        TAparrafo.setPreferredSize(new java.awt.Dimension(380, 110));
        TAparrafo.setVerifyInputWhenFocusTarget(false);
        pnlStart.add(TAparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 460, 230));

        LbContinuar.setForeground(new java.awt.Color(255, 153, 0));
        LbContinuar.setText("Presione cualquier tecla para continuar...");
        pnlStart.add(LbContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 260, -1));

        LbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LbTitulo.setText("\"\"");
        pnlStart.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        BtnResponder.setForeground(new java.awt.Color(255, 153, 0));
        BtnResponder.setText("Ir a la pregunta");
        BtnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResponderActionPerformed(evt);
            }
        });
        pnlStart.add(BtnResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarBoton(){
        BtnResponder.setVisible(true);
            BtnResponder.setEnabled(true);
            LbContinuar.setVisible(false);
    }
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.print(alma_etapa);
        if (alma_etapa == 0) {
            mostrarBoton();
            LbTitulo.setText("ALMA EN LA ESCUELA");
            TAparrafo.setText("""
                              La guajira en materia agrícola produce diferentes productos como lo son: maíz en los municipios de Hatonuevo, Albania, el Molino, San Juan del Cesar y Barrancas, el plátano en los municipios de Dibulla, el arroz en el municipio de Distracción y Fonseca, el café en La Jagua del Pilar, Villanueva y Urumita, el frijol en Maicao y la yuca en Riohacha, según el EVA 2021.
                              Alma debe identificar sus raíces y los productos autóctonas de la zona geográfica.
                              															
                              """);

        }

        if (alma_etapa == 1) {
            mostrarBoton();
            LbTitulo.setText("URIMITA");
            TAparrafo.setText("""
                              Urumita es hogar de por lo menos 500 familias que dependen del café para su sustento. Urumita produce café arábigo de altura, pero no tienen maquinaria para procesarlo. Los intermediarios les pagan 2,000 por kilo y lo venden en 20,000.""");
        }
        if (alma_etapa == 2) {
            mostrarBoton();
            LbTitulo.setText("MUNICIPIO DE DISTRACOM");
            TAparrafo.setText("""
                              Un nativo agrónomo le dice: Que esta semilla ancestral resiste sequías, pero casi no se usa, que la mayoría  de los jóvenes se van a Venezuela por falta de oportunidades. """);
        }
        if (alma_etapa == 3) {
            mostrarBoton();
            LbTitulo.setText("RIOHACHA");
            TAparrafo.setText("""
                              Una de las primeras cosas que observa es como niños muy pequeños y parecidos a los de su natal municipio de igual manera flacos buscan comida hasta en cestas de basura. Lleva su inquietud a su maestra le dice que
                              El pescado es el principal alimento, pero la contaminación por plásticos redujo la pesca en 40% (INVEMAR, 2023) y Los comedores comunitarios solo dan alimento 3 días a la semana.""");
        }
        if (alma_etapa == 4) {
            mostrarBoton();
            LbTitulo.setText("CARTAGENA");
            TAparrafo.setText("""
                              En categena de Indias, Hay huertos urbanos, pero las personas no saben cocinar lo que cosechan. """);
                                }
        if (alma_etapa == 5) {
            mostrarBoton();
            LbTitulo.setText("¿Por qué se crearon los ODS?");
            TAparrafo.setText("""
                              Alma conoce a mujeres afro que cultivan chontaduro, pero no pueden venderlo. Una líder le cuenta:
                              Los mercados están lejos y el transporte es caro y los hombres controlan los ingresos familiares.""");
        }
        if (alma_etapa == 6) {

            /*
             */
            menuHistoria menuH = new menuHistoria();
            dispose();

            menuH.setVisible(true);
        }


    }//GEN-LAST:event_formKeyPressed

    private void BtnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResponderActionPerformed
        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        LbContinuar.setVisible(true);
        almaPreguntas Alma = new almaPreguntas();
        dispose();
        Alma.setVisible(true);
    }//GEN-LAST:event_BtnResponderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnResponder;
    private javax.swing.JLabel LbContinuar;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextArea TAparrafo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlStart;
    // End of variables declaration//GEN-END:variables
}
