/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import static challenge04.main.alma_etapa;
import static challenge04.main.alma_correcta;
import static challenge04.main.vidas_historia;
import javax.sound.sampled.*;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS
 */
public class almaPreguntas extends javax.swing.JFrame {

    String[] preguntas = {
        "¿Qué producto se da en su natal Urumita?",
        "El pensamiento que tiene a Alma respecto a esto sería, Que en futuro se podría:",
        "El nativo le pregunta a Alma ¿Qué acción revitalizaría la economía local? ",
        "La maestra le pregunta a Alma: ¿Qué solución combate el hambre y protege el mar simultáneamente?",
        "¿Qué proyecto integrado combate el hambre aquí?",
        "¿Cómo empoderar a estas mujeres y combatir el hambre? "
    };

    String[][] opciones = {
        {"Maíz", "Arroz", "Café", "Frijol"},
        {"Pedir subsidios al gobierno", "Montar un taller local para tostar y empacar el café", "Vender el café a multinacionales", "Cambiar a cultivos de coca"},
        {"Usar transgénicos para aumentar producción", "Crear un banco de semillas de frijol guajiro y venderlo como producto gourmet", "Convertir la tierra en pastizales para ganado", "Esperar lluvias"},
        {"Repartir más comida procesada ", "Crear una red de pesca sostenible y limpieza de manglares", "Importar carne de res", "Construir un puerto pesquero industrial"},
        {"Dar bonos para comprar en supermercados", "Talleres de cocina con productos de huertos + venta de excedentes", "Repartir suplementos de hierro ", "Construir un McDonald`s comunitario"},
        {"Pedir ayuda a ONGs internacionales", "Crear una cooperativa de mujeres para hacer harina de chontaduro ", "Esperar a que el gobierno construya carreteras", "Vender las tierras a empresas"}
    };

    public almaPreguntas() {
        initComponents();
        reproducirSonido();
        int i = alma_etapa;
        switch (vidas_historia) {
                case 1:
                    lbvida1.setVisible(true);
                    lbvida2.setVisible(false);
                    lbvida3.setVisible(false);
                    break;
                    case 2:
                    lbvida1.setVisible(true);
                    lbvida2.setVisible(true);
                    lbvida3.setVisible(false);
                    break;
                    case 3:
                    lbvida1.setVisible(true);
                    lbvida2.setVisible(true);
                    lbvida3.setVisible(true);
                    break;
                default:
                    throw new AssertionError();
            }
        LbPregunta.setText(preguntas[i]);
        RB1.setText(opciones[i][0]);
        RB2.setText(opciones[i][1]);
        RB3.setText(opciones[i][2]);
        RB4.setText(opciones[i][3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbPregunta = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        BtnRespuesta = new javax.swing.JButton();
        lbvida1 = new javax.swing.JLabel();
        lbvida2 = new javax.swing.JLabel();
        lbvida3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alma_Niña .png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHALLENGE 04");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alma_Niña .png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        LbPregunta.setForeground(new java.awt.Color(255, 153, 0));
        LbPregunta.setText("\"\"");
        LbPregunta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(RB1);

        buttonGroup1.add(RB2);

        buttonGroup1.add(RB3);

        buttonGroup1.add(RB4);

        BtnRespuesta.setForeground(new java.awt.Color(255, 153, 0));
        BtnRespuesta.setText("Enviar  Respuesta");
        BtnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRespuestaActionPerformed(evt);
            }
        });

        lbvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N

        lbvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N

        lbvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB1)
                            .addComponent(RB2)
                            .addComponent(RB3)
                            .addComponent(RB4)
                            .addComponent(LbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(190, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbvida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbvida2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbvida3)
                        .addGap(4, 4, 4))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(LbPregunta))
                            .addComponent(jLabel4)))
                    .addComponent(lbvida3)
                    .addComponent(lbvida2)
                    .addComponent(lbvida1))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(RB1)
                        .addGap(9, 9, 9)
                        .addComponent(RB2)
                        .addGap(9, 9, 9)
                        .addComponent(RB3)
                        .addGap(9, 9, 9)
                        .addComponent(RB4)
                        .addGap(29, 29, 29)
                        .addComponent(BtnRespuesta))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRespuestaActionPerformed
        int alma_respuesta = 0;
        if (buttonGroup1.getSelection() != null) {

            if (RB1.isSelected()) {
                alma_respuesta = 1;
            } else if (RB2.isSelected()) {
                alma_respuesta = 2;
            } else if (RB3.isSelected()) {
                alma_respuesta = 3;
            } else if (RB4.isSelected()) {
                alma_respuesta = 4;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ninguna opción seleccionada");
            
        }
        if (alma_correcta[alma_etapa] == alma_respuesta) {
            alma_etapa++;
            LbPregunta.setText("");
            dispose();
            alma Alma = new alma();
            Alma.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error, intente nuevamente");
            vidas_historia--;
            dispose();
            alma Alma = new alma();
            Alma.setVisible(true);
        }

    }//GEN-LAST:event_BtnRespuestaActionPerformed
    private void reproducirSonido() {
        try {
            // Esta línea busca el archivo desde la carpeta src/sonidos/
            InputStream inputStream = getClass().getClassLoader().getResourceAsStream("sonidos/avesDeFondo.wav");

            if (inputStream == null) {
                JOptionPane.showMessageDialog(this, "Archivo no encontrado. Verifica la ruta y el nombre.");
                return;
            }

            AudioInputStream audioStream = AudioSystem.getAudioInputStream(inputStream);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al reproducir sonido: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(almaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new almaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRespuesta;
    private javax.swing.JLabel LbPregunta;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbvida1;
    private javax.swing.JLabel lbvida2;
    private javax.swing.JLabel lbvida3;
    // End of variables declaration//GEN-END:variables
}
