/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import static challenge04.main.vidas_historia;
import static challenge04.main.edu_etapa;

/**
 *
 * @author david
 */
public class edu extends javax.swing.JFrame {

    String[] titulos = {
        "EDU",
        "EDU EN EL CAQUETA",
        "JOVENES ARHUACOS",
        "EL PATIA CAUCA",
        "TUMACO",
        "RETORNO A CARTAGENA"
    };
    String[] contextos = {
        "Edu es un sabio viajero que recorre Colombia compartiendo conocimientos con niños, jóvenes y adultos. Guía natural y respetuoso de todas las culturas, defiende con pasión el derecho a una educación de calidad.",
        "Edu llega a una comunidad rural en Caquetá, donde los niños aprenden debajo de un árbol, sin cuadernos ni pupitres",
        "Edu se encuentra con jovenes de talla mediana, piel oscura, rostro ovalado y nariz recta y aguileña son jovenes Arhuacos",
        "Edu visita un colegio urbano en el Patia, donde los jóvenes dicen que <<la escuela no sirve para la vida real.>>",
        "En TUMACO, es una realidad compleja marcada por la presencia de diversos actores armados que se disputan el control territorial para el ejercicio de economías ilícitas",
        "Edu recorrio, gran parte del país repartiendo conocimiento y aprendiendo cada vez de los diferentes pueblos visitados"
    };

    public edu() {
        initComponents();

        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        lbl_btn_responder.setVisible(false);

        LbTitulo.setText(titulos[edu_etapa]);
        TAparrafo.setText(contextos[edu_etapa]);
        switch (vidas_historia) {
            case 1 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
            }
            case 2 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(false);
            }
            case 3 -> {
                lbvida1.setVisible(true);
                lbvida2.setVisible(true);
                lbvida3.setVisible(true);
            }
            default -> {
                lbvida1.setVisible(false);
                lbvida2.setVisible(false);
                lbvida3.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TAparrafo = new javax.swing.JTextArea();
        LbContinuar = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        BtnResponder = new javax.swing.JButton();
        lbl_btn_responder = new javax.swing.JLabel();
        lbvida1 = new javax.swing.JLabel();
        lbvida2 = new javax.swing.JLabel();
        lbvida3 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Challenge04");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlStart.setBackground(new java.awt.Color(255, 255, 255));
        pnlStart.setMinimumSize(new java.awt.Dimension(480, 480));
        pnlStart.setPreferredSize(new java.awt.Dimension(480, 488));
        pnlStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        pnlStart.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        TAparrafo.setEditable(false);
        TAparrafo.setBackground(new java.awt.Color(255, 255, 255));
        TAparrafo.setColumns(20);
        TAparrafo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TAparrafo.setForeground(new java.awt.Color(255, 255, 255));
        TAparrafo.setLineWrap(true);
        TAparrafo.setRows(5);
        TAparrafo.setWrapStyleWord(true);
        TAparrafo.setAutoscrolls(false);
        TAparrafo.setBorder(null);
        TAparrafo.setFocusable(false);
        TAparrafo.setOpaque(false);
        TAparrafo.setPreferredSize(new java.awt.Dimension(380, 110));
        TAparrafo.setVerifyInputWhenFocusTarget(false);
        pnlStart.add(TAparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 660, 220));

        LbContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbContinuar.setForeground(new java.awt.Color(255, 153, 0));
        LbContinuar.setText("Presione cualquier tecla para continuar...");
        pnlStart.add(LbContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 290, -1));

        LbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(255, 153, 0));
        LbTitulo.setText("\"\"");
        pnlStart.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        BtnResponder.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        BtnResponder.setForeground(new java.awt.Color(255, 255, 255));
        BtnResponder.setText("Ir a la pregunta");
        BtnResponder.setBorder(null);
        BtnResponder.setBorderPainted(false);
        BtnResponder.setContentAreaFilled(false);
        BtnResponder.setFocusPainted(false);
        BtnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResponderActionPerformed(evt);
            }
        });
        pnlStart.add(BtnResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 433, 170, 50));

        lbl_btn_responder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        pnlStart.add(lbl_btn_responder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 200, 60));

        lbvida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        lbvida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        lbvida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vida.gif"))); // NOI18N
        pnlStart.add(lbvida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background_general.png"))); // NOI18N
        pnlStart.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStart, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStart, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarBoton() {
        BtnResponder.setVisible(true);
        BtnResponder.setEnabled(true);
        lbl_btn_responder.setVisible(true);
        LbContinuar.setVisible(false);
    }
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.print(edu_etapa);
        if (edu_etapa == 0) {
            mostrarBoton();
            LbTitulo.setText("EL GÉNESIS DE EDU");
            TAparrafo.setText("""
                              Su vocación nació en Cartagena, inspirado por su abuela, una maestra jubilada que le contaba historias de niños en lugares remotos donde no llegaban ni libros ni maestros.
                              Desde entonces, Edu se convirtió en símbolo del poder transformador del aprendizaje.
                              															
                              """);

        }

        if (edu_etapa == 1) {
            mostrarBoton();
            LbTitulo.setText("ESCUELA EN EL CAQUETA");
            TAparrafo.setText("""
                              La maestra de la escuela le cuenta que no tienen conexión a internet ni materiales, pero sí muchas ganas de aprender. """);
        }
        if (edu_etapa == 2) {
            mostrarBoton();
            LbTitulo.setText("REUNION CON LOS JOVENES");
            TAparrafo.setText("""
                              En un encuentro con estos jóvenes, Edu escucha cómo los saberes tradicionales son ignorados en la escuela formal. Los estudiantes se sienten poco representados """);
        }
        if (edu_etapa == 3) {
            mostrarBoton();
            LbTitulo.setText("EL PATIA");
            TAparrafo.setText("""
                              Una profesora del interior del Patia, de un Pueblo de nombre La Fonda, le comenta que muchos desertan por falta de motivación""");
        }
        if (edu_etapa == 4) {
            mostrarBoton();
            LbTitulo.setText("TUMACO");
            TAparrafo.setText("""
                              En Tumaco, Edu visita una escuela afectada por el conflicto armado, Algunos niños han perdido familiares, y hay miedo de ir a clase.""");
        }
        if (edu_etapa == 5) {
            mostrarBoton();
            LbTitulo.setText("COMPARTIENDO CONOCIMIENTO");
            TAparrafo.setText("""
                              De regreso en Cartagena, Edu organiza un festival de aprendizaje con niños, docentes y familias de todo el país, 
                              Comparte historias de su viaje y celebra los logros de cada comunidad.""");
        }


        /*
         */

    }//GEN-LAST:event_formKeyPressed

    private void BtnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResponderActionPerformed
        BtnResponder.setVisible(false);
        BtnResponder.setEnabled(false);
        lbl_btn_responder.setVisible(false);
        LbContinuar.setVisible(true);
        eduPreguntas Edu = new eduPreguntas();
        dispose();
        Edu.setVisible(true);
    }//GEN-LAST:event_BtnResponderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnResponder;
    private javax.swing.JLabel LbContinuar;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextArea TAparrafo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_btn_responder;
    private javax.swing.JLabel lbvida1;
    private javax.swing.JLabel lbvida2;
    private javax.swing.JLabel lbvida3;
    private javax.swing.JPanel pnlStart;
    // End of variables declaration//GEN-END:variables
}
