/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import GUI.*;

/**
 *
 * @author david
 */
public class llimbo extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public llimbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TAparrafo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Challenge04");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlStart.setBackground(new java.awt.Color(255, 255, 255));
        pnlStart.setMinimumSize(new java.awt.Dimension(480, 480));
        pnlStart.setPreferredSize(new java.awt.Dimension(480, 488));
        pnlStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        pnlStart.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        TAparrafo.setEditable(false);
        TAparrafo.setBackground(new java.awt.Color(255, 255, 255));
        TAparrafo.setColumns(20);
        TAparrafo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TAparrafo.setForeground(new java.awt.Color(0, 102, 102));
        TAparrafo.setLineWrap(true);
        TAparrafo.setRows(5);
        TAparrafo.setText("Los Objetivos de Desarrollo Sostenible (ODS) son una serie de metas que la ONU propuso en el año 2015 como parte de la llamada Agenda 2030. Básicamente, son un plan global para mejorar el mundo en temas como la pobreza, el medio ambiente, la educación y la igualdad.  Son 17 objetivos interconectados que abarcan pobreza, medio ambiente, educación e igualdad, entre otros temas cruciales.");
        TAparrafo.setWrapStyleWord(true);
        TAparrafo.setAutoscrolls(false);
        TAparrafo.setBorder(null);
        TAparrafo.setFocusable(false);
        TAparrafo.setPreferredSize(new java.awt.Dimension(380, 110));
        TAparrafo.setVerifyInputWhenFocusTarget(false);
        pnlStart.add(TAparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 460, 200));

        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Presione cualquier tecla para continuar...");
        pnlStart.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 260, -1));

        LbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LbTitulo.setText("¿Qué son los Objetivos de Desarrollo Sostenible?");
        pnlStart.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int estado = 0;
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        estado++;

        if (estado == 1) {
            LbTitulo.setText("Agenda 2030");
            TAparrafo.setText("""
                              Los ODS son un plan global propuesto por la ONU en 2015 como parte de la Agenda 2030 para mejorar el mundo en temas clave.
                              
                              Acci\u00f3n Ciudadana
                              No solo los gobiernos deben actuar; como ciudadanos, podemos contribuir desde nuestros roles, incluso como estudiantes""");

        }
        if (estado == 2) {
            LbTitulo.setText("objetiivos de desarrollo sosttennible");
            TAparrafo.setText("""
                              Este proyecto explora los Objetivos de Desarrollo Sostenible (ODS) de la ONU, un llamado global para:
                              ☺Erradicar la pobreza,
                              ☺Proteger el planeta,
                              ☺Asegurar la prosperidad para todos.
                              Analizaremos su origen, importancia y c\u00f3mo Colombia est\u00e1 trabajando para alcanzar estas metas antes de 2030. Tambi\u00e9n exploraremos los desaf\u00edos y oportunidades que presenta la implementaci\u00f3n de los ODS en el contexto colombiano.""");
        }
        if (estado == 3) {
            LbTitulo.setText("¿Por qué se crearon los ODS?");
            TAparrafo.setText("""
                              Los ODS surgieron como una necesidad para combatir problemas como:
                              \u263aDesigualdad econ\u00f3mica,
                              \u263aPobreza extrema,
                              \u263aCambio clim\u00e1tico.
                              Vivimos en una sociedad desigual donde algunas personas tienen mucho dinero y otras muy poco. Esto limita el acceso a necesidades b\u00e1sicas (servicios esenciales, alimentos, educaci\u00f3n), generando pobreza no solo material, sino tambi\u00e9n mental.
                              Los ODS son un plan global propuesto por la ONU en 2015 como parte de la Agenda 2030 para mejorar el mundo en temas clave.""");
        } if (estado ==4){
        
        /*
        */
        
        menuHistoria menuH = new menuHistoria();
        dispose();
        
        menuH.setVisible(true);
        }

        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(llimbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(llimbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(llimbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(llimbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new llimbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextArea TAparrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlStart;
    // End of variables declaration//GEN-END:variables
}
