/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import GUI.*;
import java.awt.*;
import javax.swing.ImageIcon;
import static challenge04.main.*;
import challenge04.sound;

/**
 *
 * @author david
 */
public class menuHistoria extends javax.swing.JFrame {

    private Point mouseClickPoint;
    ImageIcon hoverBtnIcon, defaultBtnIcon, disabledBtnIcon, hoverBtnCloseIcon, defaultBtnCloseIcon, hoverBtnMiniIcon, defaultBtnMiniIcon;
    /**
     * Creates new form menu
     */
    public menuHistoria() {
        initComponents();
        hoverBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn-active.png"));
        defaultBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn.png"));
        disabledBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn-disabled.png"));
        
        hoverBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close-active.png"));
        defaultBtnCloseIcon = new ImageIcon(getClass().getResource("/imagenes/message/btn-message-close.png"));
        
        hoverBtnMiniIcon = new ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini-active.png"));
        defaultBtnMiniIcon = new ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini.png"));
        

        scrl_message.setOpaque(false);
        scrl_message.getViewport().setOpaque(false);
        
        BtnAlma.setText("Alma (ODS 2)");
        if(alma_etapa_bloqueada){
            BtnAlma.setText("Alma (ODS 2) (bloqueado)");
            lbl_btn_alma.setIcon(disabledBtnIcon);
        }
        
        BtnEDu.setText("Edu (ODS 4)");
        if(edu_etapa_bloqueada){
            BtnEDu.setText("Edu (ODS 4) (bloqueado)");
            lbl_btn_edu.setIcon(disabledBtnIcon);
        }
        
        if(!modo_historia_completa){
            lbl_palabra_clave.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_bar = new javax.swing.JPanel();
        lbl_close_window = new javax.swing.JLabel();
        lbl_mini_window = new javax.swing.JLabel();
        BtnLimbo = new javax.swing.JButton();
        lbl_btn_limbo = new javax.swing.JLabel();
        BtnAlma = new javax.swing.JButton();
        lbl_btn_alma = new javax.swing.JLabel();
        BtnEDu = new javax.swing.JButton();
        lbl_btn_edu = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        lbl_btn_volver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_sound = new javax.swing.JLabel();
        scrl_message = new javax.swing.JScrollPane();
        lbl_palabra_clave = new javax.swing.JTextArea();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Challenge04 - Menú Principal");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bar.setOpaque(false);
        pnl_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barMouseDragged(evt);
            }
        });
        pnl_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barMousePressed(evt);
            }
        });
        pnl_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/message/btn-message-close.png"))); // NOI18N
        lbl_close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_close_windowMouseExited(evt);
            }
        });
        pnl_bar.add(lbl_close_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 50));

        lbl_mini_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bar/btn-icon-mini.png"))); // NOI18N
        lbl_mini_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_mini_windowMouseExited(evt);
            }
        });
        pnl_bar.add(lbl_mini_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, 50));

        jPanel1.add(pnl_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        BtnLimbo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnLimbo.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimbo.setText("Limbo");
        BtnLimbo.setBorder(null);
        BtnLimbo.setBorderPainted(false);
        BtnLimbo.setContentAreaFilled(false);
        BtnLimbo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimbo.setFocusPainted(false);
        BtnLimbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLimboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLimboMouseExited(evt);
            }
        });
        BtnLimbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimboActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 190, 160, 40));

        lbl_btn_limbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_limbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 60));

        BtnAlma.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BtnAlma.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlma.setText("Alma (ODS) (bloqueado)");
        BtnAlma.setBorder(null);
        BtnAlma.setBorderPainted(false);
        BtnAlma.setContentAreaFilled(false);
        BtnAlma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlma.setFocusPainted(false);
        BtnAlma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAlmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAlmaMouseExited(evt);
            }
        });
        BtnAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlmaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 260, 170, 40));

        lbl_btn_alma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_alma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 190, 60));

        BtnEDu.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BtnEDu.setForeground(new java.awt.Color(255, 255, 255));
        BtnEDu.setText("Edu (ODS 4) (bloqueado)");
        BtnEDu.setBorder(null);
        BtnEDu.setBorderPainted(false);
        BtnEDu.setContentAreaFilled(false);
        BtnEDu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEDu.setFocusPainted(false);
        BtnEDu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEDuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEDuMouseExited(evt);
            }
        });
        BtnEDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDuActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 330, 170, 40));

        lbl_btn_edu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 190, 60));

        btn_volver.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.setBorder(null);
        btn_volver.setBorderPainted(false);
        btn_volver.setContentAreaFilled(false);
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.setFocusPainted(false);
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_volverMouseExited(evt);
            }
        });
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 170, 40));

        lbl_btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lbl_sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sound-icon.png"))); // NOI18N
        lbl_sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_soundMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 60, 60));

        scrl_message.setBorder(null);
        scrl_message.setForeground(new java.awt.Color(255, 153, 0));
        scrl_message.setOpaque(false);

        lbl_palabra_clave.setColumns(20);
        lbl_palabra_clave.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbl_palabra_clave.setForeground(new java.awt.Color(255, 255, 255));
        lbl_palabra_clave.setLineWrap(true);
        lbl_palabra_clave.setRows(5);
        lbl_palabra_clave.setText("¡Felicidades, valiente! Has conquistado el modo historia.\nRecuerda esta palabra sagrada, pues abrirá puertas en el futuro: ARREBOL.");
        lbl_palabra_clave.setWrapStyleWord(true);
        lbl_palabra_clave.setBorder(null);
        lbl_palabra_clave.setOpaque(false);
        scrl_message.setViewportView(lbl_palabra_clave);

        jPanel1.add(scrl_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 390, 300, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background-historia.png"))); // NOI18N
        jPanel1.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimboActionPerformed
     dispose();
     llimbo Limbo = new llimbo();
     Limbo.setVisible(true);
    }//GEN-LAST:event_BtnLimboActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        menu Menu = new menu();
        dispose();
        Menu.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void BtnAlmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlmaActionPerformed
        if(alma_etapa_bloqueada){
            return;
        }
        alma Alma = new alma();
        dispose();
        Alma.setVisible(true);
    }//GEN-LAST:event_BtnAlmaActionPerformed

    private void BtnEDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDuActionPerformed
        if(edu_etapa_bloqueada){
            return;
        }
        edu Edu = new edu();
        dispose();
        Edu.setVisible(true);
    }//GEN-LAST:event_BtnEDuActionPerformed

    private void BtnLimboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimboMouseEntered
        // TODO add your handling code here:
        lbl_btn_limbo.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnLimboMouseEntered

    private void BtnLimboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimboMouseExited
        // TODO add your handling code here:
        lbl_btn_limbo.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnLimboMouseExited

    private void BtnAlmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlmaMouseEntered
        // TODO add your handling code here:
        if(alma_etapa_bloqueada){
            return;
        }
        lbl_btn_alma.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnAlmaMouseEntered

    private void BtnAlmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlmaMouseExited
        // TODO add your handling code here:
        if(alma_etapa_bloqueada){
            return;
        }
        lbl_btn_alma.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnAlmaMouseExited

    private void BtnEDuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDuMouseEntered
        // TODO add your handling code here:
        if(edu_etapa_bloqueada){
            return;
        }
        lbl_btn_edu.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnEDuMouseEntered

    private void BtnEDuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDuMouseExited
        // TODO add your handling code here:
        if(edu_etapa_bloqueada){
            return;
        }
        lbl_btn_edu.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnEDuMouseExited

    private void btn_volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseEntered
        // TODO add your handling code here:
        lbl_btn_volver.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_volverMouseEntered

    private void btn_volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseExited
        // TODO add your handling code here:
        lbl_btn_volver.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_volverMouseExited

    private void lbl_close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_close_windowMouseClicked

    private void lbl_close_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseEntered
        // TODO add your handling code here:
        lbl_close_window.setIcon(hoverBtnCloseIcon);
    }//GEN-LAST:event_lbl_close_windowMouseEntered

    private void lbl_close_windowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_windowMouseExited
        // TODO add your handling code here:
        lbl_close_window.setIcon(defaultBtnCloseIcon);
    }//GEN-LAST:event_lbl_close_windowMouseExited

    private void lbl_mini_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseClicked
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbl_mini_windowMouseClicked

    private void lbl_mini_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseEntered
        // TODO add your handling code here:
        lbl_mini_window.setIcon(hoverBtnMiniIcon);
    }//GEN-LAST:event_lbl_mini_windowMouseEntered

    private void lbl_mini_windowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mini_windowMouseExited
        // TODO add your handling code here:
        lbl_mini_window.setIcon(defaultBtnMiniIcon);
    }//GEN-LAST:event_lbl_mini_windowMouseExited

    private void pnl_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barMouseDragged
        // TODO add your handling code here:
        Point frameLocation = getLocation();
        int x = frameLocation.x + evt.getX() - mouseClickPoint.x;
        int y = frameLocation.y + evt.getY() - mouseClickPoint.y;
        setLocation(x, y);
    }//GEN-LAST:event_pnl_barMouseDragged

    private void pnl_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barMousePressed
        // TODO add your handling code here:
        mouseClickPoint = evt.getPoint();
    }//GEN-LAST:event_pnl_barMousePressed

    private void lbl_soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_soundMouseClicked
        // TODO add your handling code here:
        sound.getInstance().reproducirSonido(this, 0);
        sound.getInstance().toogleBackgroundAudio();
        lbl_sound.setIcon(sound.getInstance().getImageIcon());
    }//GEN-LAST:event_lbl_soundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuHistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlma;
    private javax.swing.JButton BtnEDu;
    private javax.swing.JButton BtnLimbo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_btn_alma;
    private javax.swing.JLabel lbl_btn_edu;
    private javax.swing.JLabel lbl_btn_limbo;
    private javax.swing.JLabel lbl_btn_volver;
    private javax.swing.JLabel lbl_close_window;
    private javax.swing.JLabel lbl_mini_window;
    private javax.swing.JTextArea lbl_palabra_clave;
    private javax.swing.JLabel lbl_sound;
    private javax.swing.JPanel pnl_bar;
    private javax.swing.JScrollPane scrl_message;
    // End of variables declaration//GEN-END:variables
}
