/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.historia;

import GUI.*;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class menuHistoria extends javax.swing.JFrame {

    ImageIcon hoverBtnIcon, defaultBtnIcon;
    /**
     * Creates new form menu
     */
    public menuHistoria() {
        initComponents();
        hoverBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn-active.png"));
        defaultBtnIcon = new ImageIcon(getClass().getResource("/imagenes/btn.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnLimbo = new javax.swing.JButton();
        lbl_btn_limbo = new javax.swing.JLabel();
        BtnAlma = new javax.swing.JButton();
        lbl_btn_alma = new javax.swing.JLabel();
        BtnEDu = new javax.swing.JButton();
        lbl_btn_edu = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        lbl_btn_volver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Challenge04 - Menú Principal");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLimbo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnLimbo.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimbo.setText("Limbo");
        BtnLimbo.setBorder(null);
        BtnLimbo.setBorderPainted(false);
        BtnLimbo.setContentAreaFilled(false);
        BtnLimbo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimbo.setFocusPainted(false);
        BtnLimbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLimboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLimboMouseExited(evt);
            }
        });
        BtnLimbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimboActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 190, 160, 40));

        lbl_btn_limbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_limbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 60));

        BtnAlma.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BtnAlma.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlma.setText("Alma (ODS) (bloqueado)");
        BtnAlma.setBorder(null);
        BtnAlma.setBorderPainted(false);
        BtnAlma.setContentAreaFilled(false);
        BtnAlma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlma.setFocusPainted(false);
        BtnAlma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAlmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAlmaMouseExited(evt);
            }
        });
        BtnAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlmaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAlma, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 260, 170, 40));

        lbl_btn_alma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_alma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 190, 60));

        BtnEDu.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BtnEDu.setForeground(new java.awt.Color(255, 255, 255));
        BtnEDu.setText("Edu (ODS 4) (bloqueado)");
        BtnEDu.setBorder(null);
        BtnEDu.setBorderPainted(false);
        BtnEDu.setContentAreaFilled(false);
        BtnEDu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEDu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEDuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEDuMouseExited(evt);
            }
        });
        BtnEDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDuActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 330, 170, 40));

        lbl_btn_edu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 190, 60));

        btn_volver.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.setBorder(null);
        btn_volver.setBorderPainted(false);
        btn_volver.setContentAreaFilled(false);
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.setFocusPainted(false);
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_volverMouseExited(evt);
            }
        });
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 170, 40));

        lbl_btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn.png"))); // NOI18N
        jPanel1.add(lbl_btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background-historia.png"))); // NOI18N
        jPanel1.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimboActionPerformed
     dispose();
     llimbo Limbo = new llimbo();
     Limbo.setVisible(true);
    }//GEN-LAST:event_BtnLimboActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        menu Menu = new menu();
        dispose();
        Menu.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void BtnAlmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlmaActionPerformed
        alma Alma = new alma();
        dispose();
        Alma.setVisible(true);
    }//GEN-LAST:event_BtnAlmaActionPerformed

    private void BtnEDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDuActionPerformed
       edu Edu = new edu();
        dispose();
        Edu.setVisible(true);
    }//GEN-LAST:event_BtnEDuActionPerformed

    private void BtnLimboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimboMouseEntered
        // TODO add your handling code here:
        lbl_btn_limbo.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnLimboMouseEntered

    private void BtnLimboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimboMouseExited
        // TODO add your handling code here:
        lbl_btn_limbo.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnLimboMouseExited

    private void BtnAlmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlmaMouseEntered
        // TODO add your handling code here:
        lbl_btn_alma.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnAlmaMouseEntered

    private void BtnAlmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlmaMouseExited
        // TODO add your handling code here:
        lbl_btn_alma.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnAlmaMouseExited

    private void BtnEDuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDuMouseEntered
        // TODO add your handling code here:
        lbl_btn_edu.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_BtnEDuMouseEntered

    private void BtnEDuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDuMouseExited
        // TODO add your handling code here:
        lbl_btn_edu.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_BtnEDuMouseExited

    private void btn_volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseEntered
        // TODO add your handling code here:
        lbl_btn_volver.setIcon(hoverBtnIcon);
    }//GEN-LAST:event_btn_volverMouseEntered

    private void btn_volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseExited
        // TODO add your handling code here:
        lbl_btn_volver.setIcon(defaultBtnIcon);
    }//GEN-LAST:event_btn_volverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuHistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlma;
    private javax.swing.JButton BtnEDu;
    private javax.swing.JButton BtnLimbo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_btn_alma;
    private javax.swing.JLabel lbl_btn_edu;
    private javax.swing.JLabel lbl_btn_limbo;
    private javax.swing.JLabel lbl_btn_volver;
    // End of variables declaration//GEN-END:variables
}
